import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "@/components/Layout";
import henceforthbanner from "../assets/henceforthbanner.png";
import cardImage from  "../assets/cardimage1.jpg";
import accomCardImage from "../assets/accomodationcardImage.jpg";
import { IoStarSharp } from "react-icons/io5";
import destination1  from "../assets/destination.png";
import destination2 from "../assets/destination2.png";
import destination3 from "../assets/destination3.png";
import homebanner from "../assets/homepagebanner.png";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {


  return (
    <>
      <Head>
        <title>airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> 
      </Head>
      <section className="h-100">
          <div className="container mb-5">
            <div className="row text-center">
              <div className="col-md-12">
                <div className="home-page text-start">
                  <img src={henceforthbanner.src} alt="" className="w-100" />
                  <div className="home-text w-100">INTRODUCING <br/><span >Henceforth</span></div>
                  <div className="home-button"><Link href="/about-us" className="btn px-4 py-2 fs-5 border-0" style={{backgroundColor:"#fff"}}>About Us</Link></div>
                </div>
                <div className="explore-items text-start">
                  <h4>Explore the world with Airbnb Clone</h4>
                  <p className="text-secondary mb-4">These popular destinations have a lot to offer.</p>
                  <div className="row">
                    <div className="col-2">
                     <div className="explore-items-card mb-3 ">
                          <div className="explore-card-image mb-3">
                          <img src={cardImage.src} alt="card_image" className="w-100 h-100 mb-3 img-fluid object-fit-cover rounded"/>
                          </div> 
                           <div className="place-name"><h6 className="m-0"> Dubai</h6></div>
                           <div className="properties"><p>5,444 Properties</p></div>
                     </div>
                    </div>
                    <div className="col-2">
                     <div className="explore-items-card mb-3 ">
                          <div className="explore-card-image mb-3">
                          <img src={cardImage.src} alt="card_image" className="w-100 h-100 mb-3 img-fluid object-fit-cover rounded"/>
                          </div> 
                           <div className="place-name"><h6 className="m-0"> Dubai</h6></div>
                           <div className="properties"><p>5,444 Properties</p></div>
                     </div>
                    </div>
                    <div className="col-2">
                     <div className="explore-items-card mb-3 ">
                          <div className="explore-card-image mb-3">
                          <img src={cardImage.src} alt="card_image" className="w-100 h-100 mb-3 img-fluid object-fit-cover rounded"/>
                          </div> 
                           <div className="place-name"><h6 className="m-0"> Dubai</h6></div>
                           <div className="properties"><p>5,444 Properties</p></div>
                     </div>
                    </div>
                    <div className="col-2">
                     <div className="explore-items-card mb-3 ">
                          <div className="explore-card-image mb-3">
                          <img src={cardImage.src} alt="card_image" className="w-100 h-100 mb-3 img-fluid object-fit-cover rounded"/>
                          </div> 
                           <div className="place-name"><h6 className="m-0"> Dubai</h6></div>
                           <div className="properties"><p>5,444 Properties</p></div>
                     </div>
                    </div>
                    <div className="col-2">
                     <div className="explore-items-card mb-3 ">
                          <div className="explore-card-image mb-3">
                          <img src={cardImage.src} alt="card_image" className="w-100 h-100 mb-3 img-fluid object-fit-cover rounded"/>
                          </div> 
                           <div className="place-name"><h6 className="m-0"> Dubai</h6></div>
                           <div className="properties"><p>5,444 Properties</p></div>
                     </div>
                    </div>
                    <div className="col-2">
                     <div className="explore-items-card mb-3 ">
                          <div className="explore-card-image mb-3">
                          <img src={cardImage.src} alt="card_image" className="w-100 h-100 mb-3 img-fluid object-fit-cover rounded"/>
                          </div> 
                           <div className="place-name"><h6 className="m-0"> Dubai</h6></div>
                           <div className="properties"><p>5,444 Properties</p></div>
                     </div>
                    </div>                   
                  </div>
                </div>
                <div className="accomodation-items text-start">
                  <h4>Popular Accomodation</h4>
                  <p className="text-secondary">Find accommodations for you and your loved ones.</p>
                  <div className="row">
                    <div className="col-3">
                      <div className="accomodation-items-card mb-3">
                        <div className="card-image mb-3">
                        <img src={accomCardImage.src} alt="card_image" className="w-100 h-100 mb-3 img-fluid object-fit-cover rounded"/>
                        </div>
                        <div className="place-name"><h6 className="m-0">Hanimaadhoo, Maldives</h6></div>
                        <div className="room-details"><p className="m-0 text-secondary">1 Single Bed</p></div>
                        <div className="card-bottom d-flex justify-content-between align-items-center">
                          <div className="card-price"> <span>$30 / night</span></div>
                          <div className="card-rating d-flex align-items-center"><span className="px-1" style={{color:"#32CD32"}}><IoStarSharp /></span><h6 className="m-0">4.5</h6></div>
                        </div>

                      </div>
                    </div>
                    <div className="col-3">
                      <div className="accomodation-items-card mb-3">
                        <div className="card-image mb-3">
                        <img src={accomCardImage.src} alt="card_image" className="w-100 h-100 mb-3 img-fluid object-fit-cover rounded"/>
                        </div>
                        <div className="place-name"><h6 className="m-0">Hanimaadhoo, Maldives</h6></div>
                        <div className="room-details"><p className="m-0 text-secondary">1 Single Bed</p></div>
                        <div className="card-bottom d-flex justify-content-between align-items-center">
                          <div className="card-price"> <span>$30 / night</span></div>
                          <div className="card-rating d-flex align-items-center"><span className="px-1" style={{color:"#32CD32"}}><IoStarSharp /></span><h6 className="m-0">4.5</h6></div>
                        </div>

                      </div>
                    </div>
                    <div className="col-3">
                      <div className="accomodation-items-card mb-3">
                        <div className="card-image mb-3">
                        <img src={accomCardImage.src} alt="card_image" className="w-100 h-100 mb-3 img-fluid object-fit-cover rounded"/>
                        </div>
                        <div className="place-name"><h6 className="m-0">Hanimaadhoo, Maldives</h6></div>
                        <div className="room-details"><p className="m-0 text-secondary">1 Single Bed</p></div>
                        <div className="card-bottom d-flex justify-content-between align-items-center">
                          <div className="card-price"> <span>$30 / night</span></div>
                          <div className="card-rating d-flex align-items-center"><span className="px-1" style={{color:"#32CD32"}}><IoStarSharp /></span><h6 className="m-0">4.5</h6></div>
                        </div>

                      </div>
                    </div>
                    <div className="col-3">
                      <div className="accomodation-items-card mb-3">
                        <div className="card-image mb-3">
                        <img src={accomCardImage.src} alt="card_image" className="w-100 h-100 mb-3 img-fluid object-fit-cover rounded"/>
                        </div>
                        <div className="place-name"><h6 className="m-0">Hanimaadhoo, Maldives</h6></div>
                        <div className="room-details"><p className="m-0 text-secondary">1 Single Bed</p></div>
                        <div className="card-bottom d-flex justify-content-between align-items-center">
                          <div className="card-price"> <span>$30 / night</span></div>
                          <div className="card-rating d-flex align-items-center"><span className="px-1" style={{color:"#32CD32"}}><IoStarSharp /></span><h6 className="m-0">4.5</h6></div>
                        </div>

                      </div>
                    </div>
                   
                  </div>

                </div>
                <div className="destinations text-start">
                  <h4>Some Top Destinations</h4>
                  <p className="text-secondary mb-4">These are some famous destination you may like.</p>
                  <div className="row">
                    <div className="col-6">
                       <div><img src={destination1.src} className="w-100" alt="destination_city" /></div>
                       <div className="row">
                       <div className="col-6"><div className="mt-4"><img src={destination2.src} className="w-100" alt="" /></div></div>
                       <div className="col-6"><div  className="mt-4"><img src={destination2.src} className="w-100" alt="" /></div></div>
                       </div>
                      
                    </div>
                    <div className="col-6">
                      <div className="row">
                        <div className="col-6"> <div><img src={destination3.src} className="w-100" alt="" /></div></div>
                        <div className="col-6"> <div><img src={destination3.src}  className="w-100" alt="" /></div></div>
                      </div>
                      <div className="row">
                        <div className="col-12">
                          <div className="mt-4"><img src={destination1.src} className="w-100" alt="" /></div>
                        </div>
                      </div>
                     
                     
                    </div>
              
                    
                    
                  </div>
                </div>
                <div className="guest-page text-start">
                  <img src={homebanner.src} alt="" className="w-100"/>
                  <div className="guest-text w-100"><span >Host guest and <br/>earn money</span></div>
                  <div className="home-button"><button className="btn px-4 py-2 fs-5 border-0" style={{backgroundColor:"#fff"}}>Host Guests</button></div>
                </div>
              </div>
            </div>
          </div>
      </section>  
    </>
  );
};

Home.getLayout =  function getLayout(page:any){
  return <Layout>{page}</Layout>
}
